# https://numtide.github.io/devshell

[[commands]]
name = "profile"
command = "echo 'rust'"
help = "show profile (rust)"

[[commands]]
name = "pc"
command = "pre-commit run --all-files --hook-stage manual"
help = "pre-commit (manual)"

[devshell]
packages = [
  # rust/cargo installed by rustup
  # rust-analyzer installed by rustup
  "bacon",
  "mold",
  "pre-commit",
  "stdenv.cc.cc.lib",
  "cmake",
  "gnumake",
  "pkg-config",
  "openssl.dev",
]

[[env]]
name = "PKG_CONFIG_PATH"
eval = "${DEVSHELL_DIR}/lib/pkgconfig"
