# https://numtide.github.io/devshell

[[commands]]
name = "profile"
command = "echo 'rust'"
help = "show profile (rust)"

[[env]]
name = "CARGO_PROFILE_DEV_CODEGEN_BACKEND"
value = "cranelift"

[[commands]]
name = "pc"
command = "pre-commit run --all-files --hook-stage manual"
help = "pre-commit (manual)"

[devshell]
packages = [
  # rust/cargo installed by rustup
  # rust-analyzer installed by rustup
  "bacon",
  "mold",
  "pre-commit",
  "stdenv.cc.cc.lib",
  "cmake",
  "gnumake",
  "pkg-config",
]
