[[language]]
name = "python"
language-servers = ["pylsp", "ruff-lsp"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = false

[language-server.ruff-lsp]
command = "ruff-lsp"

[language-server.pylsp.config.pylsp]
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = true

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
