[[language]]
name = "python"
language-servers = ["ruff", "astral-ty"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = false

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

# disabled: not registered via language-servers above.
# using ty instead.
[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = true, maxLineLength = 120}
ruff = {enabled = true, maxLineLength = 120 }
pylsp_mypy = {enabled = true, live_mode = true}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}

[language-server.astral-ty]
command = "ty"
args= ["server"]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
